/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


/**
 *
 * @author Kelen
 */

public class Cadastro extends javax.swing.JFrame {
Modell.Cadastro cadastrado = new Modell.Cadastro();
   
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNome = new javax.swing.JLabel();
        jtxtNomeCadastro = new javax.swing.JTextField();
        jLabelemailcadastro = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabelsenhacadastro = new javax.swing.JLabel();
        jPasswordFieldsenhacadastro = new javax.swing.JPasswordField();
        jbtnSalvar = new javax.swing.JButton();
        jLabelfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblNome.setBackground(new java.awt.Color(0, 255, 255));
        jlblNome.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jlblNome.setForeground(new java.awt.Color(255, 255, 255));
        jlblNome.setText("Id Usuário");
        getContentPane().add(jlblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(jtxtNomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 205, -1));

        jLabelemailcadastro.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabelemailcadastro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelemailcadastro.setText("E-mail:");
        getContentPane().add(jLabelemailcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 205, -1));

        jLabelsenhacadastro.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabelsenhacadastro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsenhacadastro.setText("Senha:");
        getContentPane().add(jLabelsenhacadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, -1));
        getContentPane().add(jPasswordFieldsenhacadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 205, -1));

        jbtnSalvar.setBackground(new java.awt.Color(255, 102, 0));
        jbtnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSalvar.setText("Salvar ");
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 130, 30));

        jLabelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/2271438-fundo-do-torneio-de-futebol-grátis-vetor.jpg"))); // NOI18N
        getContentPane().add(jLabelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 331));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        
        cadastrado.setIdusuario(Integer.parseInt(jtxtNomeCadastro.getText())); // converti o id pois era inteiro no campo texto
        cadastrado.setEmail(jtxtEmail.getText());
        cadastrado.setSenha(jPasswordFieldsenhacadastro.getText());
                
                     
             
        
        
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelemailcadastro;
    private javax.swing.JLabel jLabelfundo;
    private javax.swing.JLabel jLabelsenhacadastro;
    private javax.swing.JPasswordField jPasswordFieldsenhacadastro;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNomeCadastro;
    // End of variables declaration//GEN-END:variables

    

    
}
