/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelen
 */
public class TelaInicialTorneio extends javax.swing.JFrame {
        
    public static boolean cadastro;

    /**
     * Creates new form TelaInicialTorneio
     */
    public TelaInicialTorneio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelfundo = new javax.swing.JPanel();
        jlblLogo = new javax.swing.JLabel();
        jlblFraseTorneio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelusuario = new javax.swing.JLabel();
        jtxtuser = new javax.swing.JTextField();
        jLabelsenha = new javax.swing.JLabel();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jButtonEntar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelfundo.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jPanelfundo.setForeground(new java.awt.Color(204, 204, 204));

        jlblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kelen\\OneDrive\\Área de Trabalho\\logo.png")); // NOI18N

        jlblFraseTorneio.setBackground(new java.awt.Color(0, 0, 0));
        jlblFraseTorneio.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jlblFraseTorneio.setForeground(new java.awt.Color(0, 0, 51));
        jlblFraseTorneio.setText("T0RNEIO ESCOLAR DE INVERNO 2022!!");
        jlblFraseTorneio.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Acesso  ao torneio.");

        jLabelusuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelusuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelusuario.setText("Usuário");

        jLabelsenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelsenha.setForeground(new java.awt.Color(0, 0, 0));
        jLabelsenha.setText("Senha");

        jPasswordFieldsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldsenhaActionPerformed(evt);
            }
        });

        jButtonEntar.setBackground(new java.awt.Color(255, 153, 0));
        jButtonEntar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEntar.setText("Entrar");
        jButtonEntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntarActionPerformed(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(255, 153, 0));
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelfundoLayout = new javax.swing.GroupLayout(jPanelfundo);
        jPanelfundo.setLayout(jPanelfundoLayout);
        jPanelfundoLayout.setHorizontalGroup(
            jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfundoLayout.createSequentialGroup()
                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelfundoLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelfundoLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabelusuario))
                    .addGroup(jPanelfundoLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabelsenha))
                    .addGroup(jPanelfundoLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfundoLayout.createSequentialGroup()
                                .addComponent(jButtonEntar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCadastrar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfundoLayout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblLogo)
                    .addComponent(jlblFraseTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        jPanelfundoLayout.setVerticalGroup(
            jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfundoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlblFraseTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelsenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelfundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEntar)
                    .addComponent(jButtonCadastrar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelfundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelfundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldsenhaActionPerformed

    private void jButtonEntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntarActionPerformed
        Menu Telademenu = new Menu();
        
        if(jtxtuser.getText().equals("TESTE") && jPasswordFieldsenha.getText().equals("123")){
            JOptionPane.showMessageDialog(null,"Acesso permitido!!", "Mensagem ao usuário", 1);
            Telademenu.setVisible(true); // pega essa tela de menu e deixa visive pra mim
            } else{
            JOptionPane.showMessageDialog(null, "Acesso negado!!", "Mensagem ao usuário", JOptionPane.ERROR_MESSAGE);
            
        }
                
    }//GEN-LAST:event_jButtonEntarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        Cadastro Teladecadastro = new Cadastro();        
        Teladecadastro.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialTorneio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEntar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelsenha;
    private javax.swing.JLabel jLabelusuario;
    private javax.swing.JPanel jPanelfundo;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JLabel jlblFraseTorneio;
    private javax.swing.JLabel jlblLogo;
    private javax.swing.JTextField jtxtuser;
    // End of variables declaration//GEN-END:variables
}
